spring:
  application:
    name: QFC2024
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qfc2024?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

#打印日志配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mybatis*/mapper/*.xml
  global-config:
    banner: false

server:
  port: 8080

attachments:
  basePath: attachments
  questions:
    one:
      folder: Question 1
      file: access.log
    two:
      folder: Question 2
      file: StringUtils.java
      output: validLineCount.txt
    three:
      folder: Question 3
      prop: sdxl_prop.txt
      template: sdxl_template.txt
      output: sdxl.txt
  save: out